name = "slapelachie"
license = "GPLv3"
#licenselink = "https://github.com/vaga/hugo-theme-m10c/blob/master/LICENSE.md"
description = "A theme to match the layout of slapelachie.xyz"
#homepage = "https://github.com/vaga/hugo-theme-m10c"
tags = ["blog", "minimalistic", "minimal", "responsive", "dark"]
features = [
  "minimalistic blog",
  "editable colors"
]
min_version = 0.55

[author]
  name = "slapelachie"
  homepage = "https://slapelacslapelachie.xyz"
